# config.yaml 示例文件
# 详细配置见 doc/config.md

# 系统基本配置
main:
  host: "0.0.0.0" # 监听地址 / 0.0.0.0 (IPV6: ::) 表示所有
  port: 9010 # 监听端口默认 9010
  debug: false # 是否启用 Flask 调试模式 (无需更改)
  timezone: "Asia/Shanghai" # 控制网页 / API 返回中时间的时区
  checkdata_interval: 30 # 多久检查一次数据是否有更改 (秒)
  secret: "" # 密钥, 更新状态时需要

# 页面内容配置
page:
  name: "User" # 你的名字
  title: "User Alive?" # 页面标题
  desc: "User's Online Status Page" # 页面详情 (用于 SEO, 或许吧)
  favicon: "/static/favicon.ico" # 页面图标 (favicon) url, 默认为 /static/favicon.ico
  background: "https://imgapi.siiway.top/image" # 背景图片 url
  learn_more_text: "GitHub Repo" # 更多信息链接的提示, 默认为 "GitHub Repo"
  learn_more_link: "https://github.com/wyf9/sleepy" # 更多信息链接的目标, 默认为本仓库链接
  more_text: "" # 内容将在状态页底部 learn_more 上方插入 (不转义)

  # hitokoto: true # 控制是否显示一言
  # canvas: true # 控制是否加载背景粒子
  # moonlight: true # 控制是否启用暗色切换 / 透明度调整
  # lantern: false # 控制是否加载节日灯笼
  # mplayer: false # 控制是否加载音乐播放器
  # zhixue: false # 控制是否加载智学网分数

# 页面状态显示配置
status:
  device_slice: 30 # 设备状态从开头截取多少文字显示 (防止窗口标题过长, 设置为 0 禁用)
  refresh_interval: 5000 # 网页多久刷新一次状态 (毫秒, 仅在回退到原始轮询方式后使用)
  not_using: "未在使用" # 锁定设备未在使用时的提示 (如为空则使用设备提交值)
  sorted: false # 控制是否对设备进行排序
  using_first: false # 控制是否将正在使用设备优先显示
  status_list: # 手动设置的状态列表
    - # status: 0
      name: "活着" # 状态名称
      desc: "目前在线，可以通过任何可用的联系方式联系本人。" # 状态描述
      color: "awake" # 状态颜色, 对应 static/style.css 中的 .sleeping .awake 等类, 可自行前往修改
    - # status: 1
      name: "似了"
      desc: "睡似了或其他原因不在线，紧急情况请使用电话联系。"
      color: "sleeping"
    # 还可添加更多自定义状态，但不要删除现有的两个状态 (可编辑)

# 可选功能
# util:
#   auto_switch_status: true # 是否启用自动切换状态
#   steam_enabled: false # 是否启用新版 Steam 状态 (iframe 框架显示, 只需要填写 ids)
#   steam_ids: "" # Steam 用户 ID
#   steam_refresh_interval: 20000 # Steam 状态刷新间隔 (毫秒)

metrics:
  enabled: true # 是否启用统计功能
  allow_list: # 将计入统计的路径列表
    - "/"
    - "/style.css"
    - "/query"
    - "/status_list"
    - "/set"
    - "/device/set"
    - "/device/remove"
    - "/device/clear"
    - "/device/private_mode"
    - "/save_data"
    - "/events"
    - "/metrics"
    - "/robots.txt"
    - "[static]" # 特殊值, 匹配 static 目录中的所有文件
    # 还可添加更多

plugin_enabled: [] # 启用的插件列表，按从上到下的顺序加载
  # - test
  # - hitokoto

plugin:
  test:
    content: "this is content defined in plugin config"
